### ISSUE TITLE
androidexample crash

### ISSUE THREAD

**Issue by fisherdev** [MailCore/mailcore2#1161]
--------- beginning of crash
07-04 01:05:30.983    8142-8142/com.fisher.mailcoredemo A/libc﹕ Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 8142 (er.mailcoredemo)
07-04 01:05:31.010    8164-8164/? E/libEGL﹕ call to OpenGL ES API with no current context (logged once per thread)
07-04 01:05:31.037    8164-8164/? W/Settings﹕ Setting android_id has moved from android.provider.Settings.System to android.provider.Settings.Secure, returning read-only value.
07-04 01:05:31.042    8164-8164/? W/Settings﹕ Setting android_id has moved from android.provider.Settings.System to android.provider.Settings.Secure, returning read-only value.
07-04 01:05:31.045    8164-8164/? W/Settings﹕ Setting android_id has moved from android.provider.Settings.System to android.provider.Settings.Secure, returning read-only value.
07-04 01:05:31.085      185-185/? I/DEBUG﹕ *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
07-04 01:05:31.085      185-185/? I/DEBUG﹕ Build fingerprint: 'google/hammerhead/hammerhead:5.1.1/LMY48B/1863243:user/release-keys'
07-04 01:05:31.085      185-185/? I/DEBUG﹕ Revision: '11'
07-04 01:05:31.085      185-185/? I/DEBUG﹕ ABI: 'arm'
07-04 01:05:31.085      185-185/? I/DEBUG﹕ pid: 8142, tid: 8142, name: er.mailcoredemo  >>> com.fisher.mailcoredemo <<<
07-04 01:05:31.085      185-185/? I/DEBUG﹕ signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
07-04 01:05:31.094      185-185/? I/DEBUG﹕ r0 a2cade9d  r1 00000000  r2 00000001  r3 00000000
07-04 01:05:31.094      185-185/? I/DEBUG﹕ r4 00000060  r5 befaed70  r6 befaee18  r7 befaeda0
07-04 01:05:31.094      185-185/? I/DEBUG﹕ r8 befaedb8  r9 b4827800  sl 00000000  fp befaed80
07-04 01:05:31.094      185-185/? I/DEBUG﹕ ip b47bef60  sp befaed40  lr a37137b1  pc 00000000  cpsr 600e0010
07-04 01:05:31.095      185-185/? I/DEBUG﹕ backtrace:
07-04 01:05:31.095      185-185/? I/DEBUG﹕ #00 pc 00000000  <unknown>
07-04 01:05:31.095      185-185/? I/DEBUG﹕ #01 pc 0026c7af  /data/dalvik-cache/arm/data@app@com.fisher.mailcoredemo-1@base.apk@classes.dex
07-04 01:05:31.147     747-1270/? W/ActivityManager﹕ getTasks: caller 10084 does not hold GET_TASKS; limiting output
07-04 01:05:31.153    747-25984/? I/ActivityManager﹕ Killing 8164:com.jingdong.app.mall/u0a84 (adj 9): kill background
07-04 01:05:31.227    747-25985/? W/ActivityManager﹕ Spurious death for ProcessRecord{16162d40 8164:com.jingdong.app.mall/u0a84}, curProc for 8164: null
07-04 01:05:31.234    1271-1271/? W/Launcher﹕ setApplicationContext called twice! old=com.google.android.velvet.VelvetApplication@32041c16 new=com.google.android.velvet.VelvetApplication@32041c16
07-04 01:05:31.251  28633-28633/? E/NetworkScheduler.SchedulerReceiver﹕ Invalid parameter app
07-04 01:05:31.251  28633-28633/? E/NetworkScheduler.SchedulerReceiver﹕ Invalid package name : Perhaps you didn't include a PendingIntent in the extras?

  android.os.DeadObjectException
            at android.os.BinderProxy.transactNative(Native Method)
            at android.os.BinderProxy.transact(Binder.java:496)
            at android.app.ApplicationThreadProxy.schedulePauseActivity(ApplicationThreadNative.java:704)
            at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:825)
            at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:2726)
            at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:2583)
            at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:2497)
            at com.android.server.am.ActivityManagerService.handleAppCrashLocked(ActivityManagerService.java:11500)
            at com.android.server.am.ActivityManagerService.makeAppCrashingLocked(ActivityManagerService.java:11397)
            at com.android.server.am.ActivityManagerService.crashApplication(ActivityManagerService.java:12081)
            at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:11592)
            at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)

**Comment by dinhviethoa** [comment]
Could you let mme know which call crashes? @DaveInAus, could you provide your opinion?

**Comment by DaveInAus** [comment]
Need more info - @fisherdev can you provide snippet of source where this is crashing

**Comment by dinhviethoa** [comment]
Probably fixed.
