### ISSUE TITLE
Android SMTPSession get error

### ISSUE THREAD

**Issue by balkarov** [MailCore/mailcore2#1382]
Hello,
I download mailcore2-android-2.aar from http://d.etpan.org/mailcore2-deps/mailcore2-android/
Add this module to my project.
When i use this `SMTPSession session = new SMTPSession();`
I get error. This error i get on android 4.2.2. On android 5 all success
```
E/dalvikvm: dlopen("/data/app-lib/com.simple.balkarov.simple-2/libMailCore.so") failed: Cannot load library: load_library(linker.cpp:750): library "/system/lib/libhoudini.so" not found
E/AndroidRuntime: FATAL EXCEPTION: main
                                                   java.lang.ExceptionInInitializerError
                                                       at com.simple.balkarov.simple.Models.Mail.send(Mail.java:26)
                                                       at com.simple.balkarov.simple.Activity.CarBMWActivity.onCreate(CarBMWActivity.java:57)
                                                       at android.app.Activity.performCreate(Activity.java:5104)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2144)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
                                                       at android.app.ActivityThread.access$600(ActivityThread.java:141)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
                                                       at android.os.Handler.dispatchMessage(Handler.java:99)
                                                       at android.os.Looper.loop(Looper.java:137)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5041)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:511)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
                                                       at dalvik.system.NativeStart.main(Native Method)
                                                    Caused by: java.lang.ExceptionInInitializerError
                                                       at com.libmailcore.NativeObject.<clinit>(NativeObject.java:42)
                                                       at com.simple.balkarov.simple.Models.Mail.send(Mail.java:26) 
                                                       at com.simple.balkarov.simple.Activity.CarBMWActivity.onCreate(CarBMWActivity.java:57) 
                                                       at android.app.Activity.performCreate(Activity.java:5104) 
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080) 
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2144) 
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230) 
                                                       at android.app.ActivityThread.access$600(ActivityThread.java:141) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                       at android.os.Looper.loop(Looper.java:137) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5041) 
                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:511) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560) 
                                                       at dalvik.system.NativeStart.main(Native Method) 
                                                    Caused by: java.lang.UnsatisfiedLinkError: Cannot load library: load_library(linker.cpp:750): library "/system/lib/libhoudini.so" not found
                                                       at java.lang.Runtime.loadLibrary(Runtime.java:371)
                                                       at java.lang.System.loadLibrary(System.java:535)
                                                       at com.libmailcore.MainThreadUtils.<init>(MainThreadUtils.java:19)
                                                       at com.libmailcore.MainThreadUtils.<clinit>(MainThreadUtils.java:9)
                                                       at com.libmailcore.NativeObject.<clinit>(NativeObject.java:42) 
                                                       at com.simple.balkarov.simple.Models.Mail.send(Mail.java:26) 
                                                       at com.simple.balkarov.simple.Activity.CarBMWActivity.onCreate(CarBMWActivity.java:57) 
                                                       at android.app.Activity.performCreate(Activity.java:5104) 
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080) 
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2144) 
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230) 
                                                       at android.app.ActivityThread.access$600(ActivityThread.java:141) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                       at android.os.Looper.loop(Looper.java:137) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5041) 
                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:511) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560) 
                                                       at dalvik.system.NativeStart.main(Native Method) 
```

**Comment by dinhviethoa** [comment]
Could you try this build instead? http://d.etpan.org/mailcore2-deps/mailcore2-android-beta/mailcore2-android-3-beta-3.aar
