### ISSUE TITLE
lib/x86/libMailCore.so: has text relocations crash

### ISSUE THREAD

**Issue by CotunaAurelian** [MailCore/mailcore2#1506]
Hello.
I've noticed that if we build a project that uses the Android **mailcore2-android-3** release library using **targetSdkVersion 24** when the IMAPSession() is called to create a new session, the application crashes with the following:
``FATAL EXCEPTION: main
                                                                         Process: com.test, PID: 18583
                                                                         java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/com.test-2/lib/x86/libMailCore.so: has text relocations
                                                                             at java.lang.Runtime.loadLibrary(Runtime.java:372)
                                                                             at java.lang.System.loadLibrary(System.java:1076)
                                                                             at com.libmailcore.MainThreadUtils.<init>(MainThreadUtils.java:19)
                                                                             at com.libmailcore.MainThreadUtils.<clinit>(MainThreadUtils.java:9)
                                                                             at com.libmailcore.MainThreadUtils.singleton(MainThreadUtils.java:0)
                                                                             at com.libmailcore.NativeObject.<clinit>(NativeObject.java:42)
                                                                             at com.test.business.web.IMAPSyncManager.<init>(IMAPSyncManager.java:39)
                                                                             at com.test.web.IMAPSyncManager.getInstance(IMAPSyncManager.java:32)
                                                                             at com.test.ui.MainActivity.onCreate(MainActivity.java:21)
                                                                             at android.app.Activity.performCreate(Activity.java:6237)
                                                                             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                             at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:148)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

I haven't found any resolution ill now on this using the latest android aar build

**Comment by hhrowal** [comment]
I was able to resolve this by upgrading to the latest NDK and then recompiling all the dependencies wit the -fPIC option in addition to the no-asm option for openssl. Then using those dependencies when recompiling libMailCore. I am now successfully running with targetSdkVersion 24.

**Comment by saenic** [comment]
I tried doing the same. I added `LOCAL_CPPFLAGS  := -fPIC` to the libraries (plus `LOCAL_CFLAGS    := -fno-asm` to openssl) and also `LOCAL_CPPFLAGS := -w -frtti -fPIC` to MailCore in Android.mk. I still get text relocation crashes on the emulator (arm works fine though).

**Comment by samiuelson** [comment]
@hhrowal Could you please share your modifications to the Android.mk and build.sh? I'm not able to generate build for x86 platform not having text relocations.

**Comment by beczesz** [comment]
Could anybody compile it to x86?

**Comment by joy88** [comment]
could you post your  Android.mk file? I puzzled by text relocation question on mac os, x86 abi @saenic

**Comment by ikyzmin** [comment]
smae issue with 28 api. Does anyone have android build for that api version?
