### ISSUE TITLE
Android: MailCore library has text relocation error

### ISSUE THREAD

**Issue by prarthnas** [MailCore/mailcore2#1649]
AndroidRuntime: FATAL EXCEPTION: main Process: com.test.example, PID: 2492 java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/com.test.example-1/lib/x86/libMailCore.so: has text relocations at java.lang.Runtime.loadLibrary0(Runtime.java:977) at java.lang.System.loadLibrary(System.java:1530) at com.libmailcore.MainThreadUtils.(MainThreadUtils.java:19) at com.libmailcore.MainThreadUtils.(MainThreadUtils.java:9) at com.libmailcore.MainThreadUtils.singleton(MainThreadUtils.java:14) at com.libmailcore.NativeObject.(NativeObject.java:42) at com.test.example.Controllers.IMAP.IMAPSessionController.createNewSession(IMAPSessionController.java:17) at com.test.example.Controllers.IMAP.IMAPSyncController.fetchFolderInfo(IMAPSyncController.kt:34) at com.test.example.Services.FolderInfoService.onStartCommand(FolderInfoService.java:48) at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3297) at android.app.ActivityThread.-wrap21(ActivityThread.java) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1565) at android.os.Handler.dispatchMessage(Handler.java:102) at android.os.Looper.loop(Looper.java:154) at android.app.ActivityThread.main(ActivityThread.java:6077) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
@dinhviethoa Crashing on emulator, any inputs?

**Comment by saenic** [comment]
I get the same crashes in **mailcore2-android-4**, so I tried fixing it like described [here](https://github.com/MailCore/mailcore2/issues/1506#issuecomment-246700366) Therefore I added `LOCAL_CPPFLAGS  := -fPIC` to the libraries (plus `LOCAL_CFLAGS    := -fno-asm` to openssl) and also `LOCAL_CPPFLAGS := -w -frtti -fPIC` to MailCore in Android.mk. I still get text relocation crashes on the emulator (arm works fine though).
