### ISSUE TITLE
error when executing autogen.sh

### ISSUE THREAD

**Issue by mattaojie** [MailCore/mailcore2#1932]
I tried to build library on android, but when I executing ./autogen.sh , I got these errors and there is no libetpan-config.h file in the folder.

```
Warning: I am going to run configure' with default arguments. If you wish to pass any others to it, please specify them on the ./autogen.sh' command line.

Running libtoolize...
libtoolize: putting auxiliary files in .'. libtoolize: copying file ./ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, m4'. libtoolize: copying file m4/libtool.m4'
libtoolize: copying file m4/ltoptions.m4' libtoolize: copying file m4/ltsugar.m4'
libtoolize: copying file m4/ltversion.m4' libtoolize: copying file m4/lt~obsolete.m4'
Running aclocal...
configure.ac:81: error: "Missing pkg-config macros"
configure.ac:81: the top level
autom4te: error: /usr/local/bin/m4 failed with exit status: 1
aclocal: error: echo failed with exit status: 1
Running autoheader...
configure.ac:81: error: "Missing pkg-config macros"
configure.ac:81: the top level
autom4te: error: /usr/local/bin/m4 failed with exit status: 1
autoheader: error: '/usr/local/bin/autom4te' failed with exit status: 1
Running autoconf ...
configure.ac:81: error: "Missing pkg-config macros"
configure.ac:81: the top level
autom4te: error: /usr/local/bin/m4 failed with exit status: 1
Running automake...
configure.ac:81: error: "Missing pkg-config macros"
configure.ac:81: the top level
autom4te: error: /usr/local/bin/m4 failed with exit status: 1
automake: error: autoconf failed with exit status: 1
Running ./configure --enable-debug ...
./autogen.sh: line 85: ./configure: No such file or directory
```

**Comment by mattaojie** [comment]
I followed the instructions exactly but I keep getting this error.

> java.lang.UnsatisfiedLinkError: dlopen failed: library "libMailCore.so" not found
>         at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
>         at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
>         at java.lang.System.loadLibrary(System.java:1664)
>         at com.libmailcore.MainThreadUtils.<init>(MainThreadUtils.java:19)
>         at com.libmailcore.MainThreadUtils.<clinit>(MainThreadUtils.java:9)
>         at com.libmailcore.MainThreadUtils.singleton(MainThreadUtils.java:14)
>         at com.libmailcore.NativeObject.<clinit>(NativeObject.java:42)
>         at com.libmailcore.androidexample.MessagesSyncManager.<init>(MessagesSyncManager.java:25)
>         at com.libmailcore.androidexample.MessagesSyncManager.singleton(MessagesSyncManager.java:19)
>         at com.libmailcore.androidexample.MessageViewListFragment.onCreate(MessageViewListFragment.java:86)
>         at android.app.Fragment.performCreate(Fragment.java:2486)
>         at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1261)
>         at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1486)
>         at android.app.FragmentManagerImpl.addFragment(FragmentManager.java:1733)
>         at android.app.FragmentManagerImpl.onCreateView(FragmentManager.java:3567)
>         at android.app.FragmentController.onCreateView(FragmentController.java:104)
>         at android.app.Activity.onCreateView(Activity.java:7228)
>         at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1086)
>         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:999)
>         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:963)
>         at android.view.LayoutInflater.inflate(LayoutInflater.java:661)
>         at android.view.LayoutInflater.inflate(LayoutInflater.java:536)
>         at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
>         at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:459)
>         at android.app.Activity.setContentView(Activity.java:3584)
>         at com.libmailcore.androidexample.MessageViewListActivity.onCreate(MessageViewListActivity.java:39)
>         at android.app.Activity.performCreate(Activity.java:8142)
>         at android.app.Activity.performCreate(Activity.java:8114)
>         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1308)
>         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3550)
>         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3749)
>         at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
>         at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
>         at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2181)
>         at android.os.Handler.dispatchMessage(Handler.java:106)
>         at android.os.Looper.loop(Looper.java:236)
>         at android.app.ActivityThread.main(ActivityThread.java:8073)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
